Feature/add some service
zipepic/AuthenticationServer pull request #27
Opened 2023-11-27 05:14 UTC by castroy10

Add some service

2023-11-27 08:21 UTC, zipepic approved these changes

2023-11-27 08:21 UTC, zipepic commented on src/main/java/com/example/authenticationserver/query/api/query/ApplicationQueryHandler.java
> +            return passwordEncoder.matches(query.getSecret(), applicationService.findById(query.getClientId()).getSecret());
Отдели ошибку не найденого приложения от ошибки неправильного пароля

2023-11-27 08:29 UTC, castroy10 commented on src/main/java/com/example/authenticationserver/query/api/query/ApplicationQueryHandler.java
> +            return passwordEncoder.matches(query.getSecret(), applicationService.findById(query.getClientId()).getSecret());
При неправильном пароле метод вернется false, а при ошибке будет выброшен exeption.
Нужно что то дополнительно?

2023-11-27 08:34 UTC, zipepic commented on src/main/java/com/example/authenticationserver/query/api/query/ApplicationQueryHandler.java
> +            return passwordEncoder.matches(query.getSecret(), applicationService.findById(query.getClientId()).getSecret());
Предлагаю проверку пароля вынести в сервис, где будет выкидываться exception, a QueryHandler будет ее обрабатывать

2023-11-27 13:18 UTC, zipepic requested changes
Все супер, теперь можно добавить в сервис транзакции

2023-11-27 20:23 UTC, zipepic reviewed
Все супер

2023-11-30 13:20 UTC, zipepic reviewed
супер

2023-11-30 13:21 UTC, zipepic reviewed
принято

2023-12-01 19:12 UTC, zipepic reviewed
супер

2023-12-01 19:13 UTC, merged